In [1]:
import pandas as pd

In [6]:
df1 = pd.read_csv(r'/Users/macuser/Documents/accenture INt/Cleaned Data/ContentCleaneds.csv')
df1

                               Content ID   Type         Category
0    97522e57-d9ab-4bd6-97bf-c24d952602d2  photo         Studying
1    9f737e0a-3cdd-4d29-9d24-753f4e3be810  photo   healthy eating
2    230c4e4d-70c3-461d-b42c-ec09396efb3f  photo   healthy eating
3    356fff80-da4d-4785-9f43-bc1261031dc6  photo       technology
4    01ab84dd-6364-4236-abbb-3f237db77180  video             food
..                                    ...    ...              ...
995  b4cef9ef-627b-41d7-a051-5961b0204ebb  video  public speaking
996  7a79f4e4-3b7d-44dc-bdef-bc990740252c    GIF       technology
997  435007a5-6261-4d8b-b0a4-55fdc189754b  audio         veganism
998  4e4c9690-c013-4ee7-9e66-943d8cbd27b7    GIF          culture
999  75d6b589-7fae-4a6d-b0d0-752845150e56  audio       technology

[1000 rows x 3 columns]

In [4]:
df2 = pd.read_csv(r'/Users/macuser/Documents/accenture INt/Cleaned Data/Reactionscleaned.csv')
df2

                                 Content ID Content Type             Datetime
0      97522e57-d9ab-4bd6-97bf-c24d952602d2      disgust  2020-11-07 09:43:50
1      97522e57-d9ab-4bd6-97bf-c24d952602d2      dislike  2021-06-17 12:22:51
2      97522e57-d9ab-4bd6-97bf-c24d952602d2       scared  2021-04-18 05:13:58
3      97522e57-d9ab-4bd6-97bf-c24d952602d2      disgust  2021-01-06 19:13:01
4      97522e57-d9ab-4bd6-97bf-c24d952602d2   interested  2020-08-23 12:25:58
...                                     ...          ...                  ...
24568  75d6b589-7fae-4a6d-b0d0-752845150e56      dislike  2020-06-27 09:46:48
24569  75d6b589-7fae-4a6d-b0d0-752845150e56    intrigued  2021-02-16 17:17:02
24570  75d6b589-7fae-4a6d-b0d0-752845150e56   interested  2020-09-12 03:54:58
24571  75d6b589-7fae-4a6d-b0d0-752845150e56      worried  2020-11-04 20:08:31
24572  75d6b589-7fae-4a6d-b0d0-752845150e56      cherish  2021-01-04 04:55:11

[24573 rows x 3 columns]

In [9]:
df3=pd.read_csv(r'/Users/macuser/Documents/accenture INt/Cleaned Data/ReactionTypes - ReactionTypes.csv.csv')
df3

   Content Type Sentiment  Score
0         heart  positive     60
1          want  positive     70
2       disgust  negative      0
3          hate  negative      5
4    interested  positive     30
5   indifferent   neutral     20
6          love  positive     65
7    super love  positive     75
8       cherish  positive     70
9         adore  positive     72
10         like  positive     50
11      dislike  negative     10
12    intrigued  positive     45
13      peeking   neutral     35
14       scared  negative     15
15      worried  negative     12

In [13]:
dfm= df1.merge(df2, how = 'inner', on='Content ID')
dfm

,Content ID,Type,Category,Content Type,Datetime
0,97522e57-d9ab-4bd6-97bf-c24d952602d2,photo,Studying,disgust,2020-11-07 09:43:50
1,97522e57-d9ab-4bd6-97bf-c24d952602d2,photo,Studying,dislike,2021-06-17 12:22:51
2,97522e57-d9ab-4bd6-97bf-c24d952602d2,photo,Studying,scared,2021-04-18 05:13:58
3,97522e57-d9ab-4bd6-97bf-c24d952602d2,photo,Studying,disgust,2021-01-06 19:13:01
4,97522e57-d9ab-4bd6-97bf-c24d952602d2,photo,Studying,interested,2020-08-23 12:25:58
...,...,...,...,...,...
24568,75d6b589-7fae-4a6d-b0d0-752845150e56,audio,technology,dislike,2020-06-27 09:46:48
24569,75d6b589-7fae-4a6d-b0d0-752845150e56,audio,technology,intrigued,2021-02-16 17:17:02
24570,75d6b589-7fae-4a6d-b0d0-752845150e56,audio,technology,interested,2020-09-12 03:54:58
24571,75d6b589-7fae-4a6d-b0d0-752845150e56,audio,technology,worried,2020-11-04 20:08:31
24572,75d6b589-7fae-4a6d-b0d0-752845150e56,audio,technology,cherish,2021-01-04 04:55:11

In [32]:
dfmm=dfm.merge(df3, how = 'inner', on='Content Type')
dfmm

,Content ID,Type,Category,Content Type,Datetime,Sentiment,Score
0,97522e57-d9ab-4bd6-97bf-c24d952602d2,photo,Studying,disgust,2020-11-07 09:43:50,negative,0
1,97522e57-d9ab-4bd6-97bf-c24d952602d2,photo,Studying,disgust,2021-01-06 19:13:01,negative,0
2,97522e57-d9ab-4bd6-97bf-c24d952602d2,photo,Studying,disgust,2021-04-09 02:46:20,negative,0
3,9f737e0a-3cdd-4d29-9d24-753f4e3be810,photo,healthy eating,disgust,2021-03-28 21:15:26,negative,0
4,230c4e4d-70c3-461d-b42c-ec09396efb3f,photo,healthy eating,disgust,2020-08-04 05:40:33,negative,0
...,...,...,...,...,...,...,...
24568,435007a5-6261-4d8b-b0a4-55fdc189754b,audio,veganism,adore,2020-10-04 22:26:33,positive,72
24569,435007a5-6261-4d8b-b0a4-55fdc189754b,audio,veganism,adore,2020-09-18 10:50:50,positive,72
24570,4e4c9690-c013-4ee7-9e66-943d8cbd27b7,GIF,culture,adore,2020-10-31 03:58:44,positive,72
24571,4e4c9690-c013-4ee7-9e66-943d8cbd27b7,GIF,culture,adore,2020-06-25 15:12:29,positive,72
24572,4e4c9690-c013-4ee7-9e66-943d8cbd27b7,GIF,culture,adore,2020-12-17 16:32:57,positive,72

In [33]:
dfmm

,Content ID,Type,Category,Content Type,Datetime,Sentiment,Score
0,97522e57-d9ab-4bd6-97bf-c24d952602d2,photo,Studying,disgust,2020-11-07 09:43:50,negative,0
1,97522e57-d9ab-4bd6-97bf-c24d952602d2,photo,Studying,disgust,2021-01-06 19:13:01,negative,0
2,97522e57-d9ab-4bd6-97bf-c24d952602d2,photo,Studying,disgust,2021-04-09 02:46:20,negative,0
3,9f737e0a-3cdd-4d29-9d24-753f4e3be810,photo,healthy eating,disgust,2021-03-28 21:15:26,negative,0
4,230c4e4d-70c3-461d-b42c-ec09396efb3f,photo,healthy eating,disgust,2020-08-04 05:40:33,negative,0
...,...,...,...,...,...,...,...
24568,435007a5-6261-4d8b-b0a4-55fdc189754b,audio,veganism,adore,2020-10-04 22:26:33,positive,72
24569,435007a5-6261-4d8b-b0a4-55fdc189754b,audio,veganism,adore,2020-09-18 10:50:50,positive,72
24570,4e4c9690-c013-4ee7-9e66-943d8cbd27b7,GIF,culture,adore,2020-10-31 03:58:44,positive,72
24571,4e4c9690-c013-4ee7-9e66-943d8cbd27b7,GIF,culture,adore,2020-06-25 15:12:29,positive,72
24572,4e4c9690-c013-4ee7-9e66-943d8cbd27b7,GIF,culture,adore,2020-12-17 16:32:57,positive,72

In [19]:
dfmm.head()
dfmm.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 24573 entries, 0 to 24572
Data columns (total 7 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Content ID    24573 non-null  object
 1   Type          24573 non-null  object
 2   Category      24573 non-null  object
 3   Content Type  24573 non-null  object
 4   Datetime      24573 non-null  object
 5   Sentiment     24573 non-null  object
 6   Score         24573 non-null  int64
dtypes: int64(1), object(6)
memory usage: 1.5+ MB

In [50]:
dfmm.columns.values[1] = "Content Type"

dfmm

,Content ID,Content Type,Category,Reaction Type,Sentiment,Score
0,97522e57-d9ab-4bd6-97bf-c24d952602d2,photo,Studying,disgust,negative,0
1,97522e57-d9ab-4bd6-97bf-c24d952602d2,photo,Studying,disgust,negative,0
2,97522e57-d9ab-4bd6-97bf-c24d952602d2,photo,Studying,disgust,negative,0
3,9f737e0a-3cdd-4d29-9d24-753f4e3be810,photo,healthy eating,disgust,negative,0
4,230c4e4d-70c3-461d-b42c-ec09396efb3f,photo,healthy eating,disgust,negative,0
...,...,...,...,...,...,...
24568,435007a5-6261-4d8b-b0a4-55fdc189754b,audio,veganism,adore,positive,72
24569,435007a5-6261-4d8b-b0a4-55fdc189754b,audio,veganism,adore,positive,72
24570,4e4c9690-c013-4ee7-9e66-943d8cbd27b7,GIF,culture,adore,positive,72
24571,4e4c9690-c013-4ee7-9e66-943d8cbd27b7,GIF,culture,adore,positive,72
24572,4e4c9690-c013-4ee7-9e66-943d8cbd27b7,GIF,culture,adore,positive,72

In [51]:
dfmm.to_csv('/Users/macuser/Documents/accenture INt/Cleaned Data/Mergedh.csv', index=False)